[project]
name = "seasons-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.4",
    "scipy>=1.15.2",
    "marimo>=0.23.0",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "altair>=5.5.0",
]

[tool.setuptools]
packages = ["seasons_py"]
